//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\Zchool\Computer Science\4º\VII Semestre\Complementos de Compilación\Tiger\Tiger\Parsing\Tiger.g4 by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public partial class TigerParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, COMMENT=41, STRING=42, INTEGER=43, ID=44, WS=45;
	public const int
		RULE_compileUnit = 0, RULE_expr = 1, RULE_lvalue = 2, RULE_decl = 3, RULE_type = 4, 
		RULE_type_fields = 5;
	public static readonly string[] ruleNames = {
		"compileUnit", "expr", "lvalue", "decl", "type", "type_fields"
	};

	private static readonly string[] _LiteralNames = {
		null, "'nil'", "'-'", "'*'", "'/'", "'+'", "'<>'", "'='", "'>='", "'<='", 
		"'>'", "'<'", "'&'", "'|'", "':='", "'('", "','", "')'", "';'", "'{'", 
		"'}'", "'['", "']'", "'of'", "'if'", "'then'", "'else'", "'while'", "'do'", 
		"'for'", "'to'", "'break'", "'let'", "'in'", "'end'", "'.'", "'type'", 
		"'var'", "':'", "'function'", "'array'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, "COMMENT", "STRING", "INTEGER", "ID", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Tiger.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	static TigerParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

	public TigerParser(ITokenStream input)
		: base(input)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class CompileUnitContext : ParserRuleContext {
		public CompileUnitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compileUnit; } }
	 
		public CompileUnitContext() { }
		public virtual void CopyFrom(CompileUnitContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ProgramContext : CompileUnitContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ProgramContext(CompileUnitContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CompileUnitContext compileUnit() {
		CompileUnitContext _localctx = new CompileUnitContext(Context, State);
		EnterRule(_localctx, 0, RULE_compileUnit);
		try {
			_localctx = new ProgramContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 12; expr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class CallContext : ExprContext {
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public CallContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCall(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParenExprsContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ParenExprsContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenExprs(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ForContext : ExprContext {
		public ExprContext e1;
		public ExprContext e2;
		public ExprContext e3;
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ForContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFor(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BreakContext : ExprContext {
		public BreakContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBreak(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LogicalContext : ExprContext {
		public ExprContext e1;
		public IToken op;
		public ExprContext e2;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public LogicalContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogical(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryMinusContext : ExprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public UnaryMinusContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryMinus(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StringContext : ExprContext {
		public ITerminalNode STRING() { return GetToken(TigerParser.STRING, 0); }
		public StringContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class WhileContext : ExprContext {
		public ExprContext e1;
		public ExprContext e2;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public WhileContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhile(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntegerContext : ExprContext {
		public ITerminalNode INTEGER() { return GetToken(TigerParser.INTEGER, 0); }
		public IntegerContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInteger(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NilContext : ExprContext {
		public NilContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNil(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ArrayContext : ExprContext {
		public ExprContext e1;
		public ExprContext e2;
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ArrayContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArray(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ComparisonContext : ExprContext {
		public ExprContext e1;
		public IToken op;
		public ExprContext e2;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ComparisonContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComparison(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AssignContext : ExprContext {
		public LvalueContext lvalue() {
			return GetRuleContext<LvalueContext>(0);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public AssignContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssign(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RecordContext : ExprContext {
		public IToken typeID;
		public ITerminalNode[] ID() { return GetTokens(TigerParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(TigerParser.ID, i);
		}
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public RecordContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRecord(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LetContext : ExprContext {
		public DeclContext[] decl() {
			return GetRuleContexts<DeclContext>();
		}
		public DeclContext decl(int i) {
			return GetRuleContext<DeclContext>(i);
		}
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public LetContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLet(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LValueContext : ExprContext {
		public LvalueContext lvalue() {
			return GetRuleContext<LvalueContext>(0);
		}
		public LValueContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IfContext : ExprContext {
		public ExprContext e1;
		public ExprContext e2;
		public ExprContext e3;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public IfContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIf(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ArithmeticContext : ExprContext {
		public ExprContext e1;
		public IToken op;
		public ExprContext e2;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ArithmeticContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArithmetic(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 2;
		EnterRecursionRule(_localctx, 2, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 116;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				{
				_localctx = new StringContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 15; Match(STRING);
				}
				break;
			case 2:
				{
				_localctx = new IntegerContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 16; Match(INTEGER);
				}
				break;
			case 3:
				{
				_localctx = new NilContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 17; Match(T__0);
				}
				break;
			case 4:
				{
				_localctx = new LValueContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 18; lvalue(0);
				}
				break;
			case 5:
				{
				_localctx = new UnaryMinusContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 19; Match(T__1);
				State = 20; expr(16);
				}
				break;
			case 6:
				{
				_localctx = new AssignContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 21; lvalue(0);
				State = 22; Match(T__13);
				State = 23; expr(10);
				}
				break;
			case 7:
				{
				_localctx = new CallContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 25; Match(ID);
				State = 26; Match(T__14);
				State = 35;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__14) | (1L << T__23) | (1L << T__26) | (1L << T__28) | (1L << T__30) | (1L << T__31) | (1L << STRING) | (1L << INTEGER) | (1L << ID))) != 0)) {
					{
					State = 27; expr(0);
					State = 32;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__15) {
						{
						{
						State = 28; Match(T__15);
						State = 29; expr(0);
						}
						}
						State = 34;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 37; Match(T__16);
				}
				break;
			case 8:
				{
				_localctx = new ParenExprsContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 38; Match(T__14);
				State = 47;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__14) | (1L << T__23) | (1L << T__26) | (1L << T__28) | (1L << T__30) | (1L << T__31) | (1L << STRING) | (1L << INTEGER) | (1L << ID))) != 0)) {
					{
					State = 39; expr(0);
					State = 44;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__17) {
						{
						{
						State = 40; Match(T__17);
						State = 41; expr(0);
						}
						}
						State = 46;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 49; Match(T__16);
				}
				break;
			case 9:
				{
				_localctx = new RecordContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 50; ((RecordContext)_localctx).typeID = Match(ID);
				State = 51; Match(T__18);
				State = 64;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ID) {
					{
					State = 52; Match(ID);
					State = 53; Match(T__6);
					State = 54; expr(0);
					State = 61;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__15) {
						{
						{
						State = 55; Match(T__15);
						State = 56; Match(ID);
						State = 57; Match(T__6);
						State = 58; expr(0);
						}
						}
						State = 63;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 66; Match(T__19);
				}
				break;
			case 10:
				{
				_localctx = new ArrayContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 67; Match(ID);
				State = 68; Match(T__20);
				State = 69; ((ArrayContext)_localctx).e1 = expr(0);
				State = 70; Match(T__21);
				State = 71; Match(T__22);
				State = 72; ((ArrayContext)_localctx).e2 = expr(6);
				}
				break;
			case 11:
				{
				_localctx = new IfContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 74; Match(T__23);
				State = 75; ((IfContext)_localctx).e1 = expr(0);
				State = 76; Match(T__24);
				State = 77; ((IfContext)_localctx).e2 = expr(0);
				State = 80;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
				case 1:
					{
					State = 78; Match(T__25);
					State = 79; ((IfContext)_localctx).e3 = expr(0);
					}
					break;
				}
				}
				break;
			case 12:
				{
				_localctx = new WhileContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 82; Match(T__26);
				State = 83; ((WhileContext)_localctx).e1 = expr(0);
				State = 84; Match(T__27);
				State = 85; ((WhileContext)_localctx).e2 = expr(4);
				}
				break;
			case 13:
				{
				_localctx = new ForContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 87; Match(T__28);
				State = 88; Match(ID);
				State = 89; Match(T__13);
				State = 90; ((ForContext)_localctx).e1 = expr(0);
				State = 91; Match(T__29);
				State = 92; ((ForContext)_localctx).e2 = expr(0);
				State = 93; Match(T__27);
				State = 94; ((ForContext)_localctx).e3 = expr(3);
				}
				break;
			case 14:
				{
				_localctx = new BreakContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 96; Match(T__30);
				}
				break;
			case 15:
				{
				_localctx = new LetContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 97; Match(T__31);
				State = 101;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__35) | (1L << T__36) | (1L << T__38))) != 0)) {
					{
					{
					State = 98; decl();
					}
					}
					State = 103;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 104; Match(T__32);
				State = 113;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__14) | (1L << T__23) | (1L << T__26) | (1L << T__28) | (1L << T__30) | (1L << T__31) | (1L << STRING) | (1L << INTEGER) | (1L << ID))) != 0)) {
					{
					State = 105; expr(0);
					State = 110;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__17) {
						{
						{
						State = 106; Match(T__17);
						State = 107; expr(0);
						}
						}
						State = 112;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 115; Match(T__33);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 135;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 133;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
					case 1:
						{
						_localctx = new ArithmeticContext(new ExprContext(_parentctx, _parentState));
						((ArithmeticContext)_localctx).e1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 118;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 119;
						((ArithmeticContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==T__2 || _la==T__3) ) {
							((ArithmeticContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 120; ((ArithmeticContext)_localctx).e2 = expr(16);
						}
						break;
					case 2:
						{
						_localctx = new ArithmeticContext(new ExprContext(_parentctx, _parentState));
						((ArithmeticContext)_localctx).e1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 121;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 122;
						((ArithmeticContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==T__1 || _la==T__4) ) {
							((ArithmeticContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 123; ((ArithmeticContext)_localctx).e2 = expr(15);
						}
						break;
					case 3:
						{
						_localctx = new ComparisonContext(new ExprContext(_parentctx, _parentState));
						((ComparisonContext)_localctx).e1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 124;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 125;
						((ComparisonContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << T__10))) != 0)) ) {
							((ComparisonContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 126; ((ComparisonContext)_localctx).e2 = expr(14);
						}
						break;
					case 4:
						{
						_localctx = new LogicalContext(new ExprContext(_parentctx, _parentState));
						((LogicalContext)_localctx).e1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 127;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 128; ((LogicalContext)_localctx).op = Match(T__11);
						State = 129; ((LogicalContext)_localctx).e2 = expr(13);
						}
						break;
					case 5:
						{
						_localctx = new LogicalContext(new ExprContext(_parentctx, _parentState));
						((LogicalContext)_localctx).e1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 130;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 131; ((LogicalContext)_localctx).op = Match(T__12);
						State = 132; ((LogicalContext)_localctx).e2 = expr(12);
						}
						break;
					}
					} 
				}
				State = 137;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class LvalueContext : ParserRuleContext {
		public LvalueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_lvalue; } }
	 
		public LvalueContext() { }
		public virtual void CopyFrom(LvalueContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class IndexLValueContext : LvalueContext {
		public LvalueContext lvalue() {
			return GetRuleContext<LvalueContext>(0);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public IndexLValueContext(LvalueContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIndexLValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdLValueContext : LvalueContext {
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public IdLValueContext(LvalueContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdLValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FieldLValueContext : LvalueContext {
		public LvalueContext lvalue() {
			return GetRuleContext<LvalueContext>(0);
		}
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public FieldLValueContext(LvalueContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFieldLValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LvalueContext lvalue() {
		return lvalue(0);
	}

	private LvalueContext lvalue(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		LvalueContext _localctx = new LvalueContext(Context, _parentState);
		LvalueContext _prevctx = _localctx;
		int _startState = 4;
		EnterRecursionRule(_localctx, 4, RULE_lvalue, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			_localctx = new IdLValueContext(_localctx);
			Context = _localctx;
			_prevctx = _localctx;

			State = 139; Match(ID);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 151;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 149;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
					case 1:
						{
						_localctx = new FieldLValueContext(new LvalueContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_lvalue);
						State = 141;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 142; Match(T__34);
						State = 143; Match(ID);
						}
						break;
					case 2:
						{
						_localctx = new IndexLValueContext(new LvalueContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_lvalue);
						State = 144;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 145; Match(T__20);
						State = 146; expr(0);
						State = 147; Match(T__21);
						}
						break;
					}
					} 
				}
				State = 153;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class DeclContext : ParserRuleContext {
		public DeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_decl; } }
	 
		public DeclContext() { }
		public virtual void CopyFrom(DeclContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class VarDeclContext : DeclContext {
		public IToken id;
		public IToken typeId;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode[] ID() { return GetTokens(TigerParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(TigerParser.ID, i);
		}
		public VarDeclContext(DeclContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVarDecl(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class TypeDeclContext : DeclContext {
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public TypeDeclContext(DeclContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeDecl(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncDeclContext : DeclContext {
		public IToken id;
		public IToken typeId;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode[] ID() { return GetTokens(TigerParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(TigerParser.ID, i);
		}
		public Type_fieldsContext type_fields() {
			return GetRuleContext<Type_fieldsContext>(0);
		}
		public FuncDeclContext(DeclContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncDecl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeclContext decl() {
		DeclContext _localctx = new DeclContext(Context, State);
		EnterRule(_localctx, 6, RULE_decl);
		int _la;
		try {
			State = 179;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__35:
				_localctx = new TypeDeclContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 154; Match(T__35);
				State = 155; Match(ID);
				State = 156; Match(T__6);
				State = 157; type();
				}
				break;
			case T__36:
				_localctx = new VarDeclContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 158; Match(T__36);
				State = 159; ((VarDeclContext)_localctx).id = Match(ID);
				State = 162;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__37) {
					{
					State = 160; Match(T__37);
					State = 161; ((VarDeclContext)_localctx).typeId = Match(ID);
					}
				}

				State = 164; Match(T__13);
				State = 165; expr(0);
				}
				break;
			case T__38:
				_localctx = new FuncDeclContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 166; Match(T__38);
				State = 167; ((FuncDeclContext)_localctx).id = Match(ID);
				State = 168; Match(T__14);
				State = 170;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ID) {
					{
					State = 169; type_fields();
					}
				}

				State = 172; Match(T__16);
				State = 175;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__37) {
					{
					State = 173; Match(T__37);
					State = 174; ((FuncDeclContext)_localctx).typeId = Match(ID);
					}
				}

				State = 177; Match(T__6);
				State = 178; expr(0);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
	 
		public TypeContext() { }
		public virtual void CopyFrom(TypeContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ArrayTypeContext : TypeContext {
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public ArrayTypeContext(TypeContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayType(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RecordTypeContext : TypeContext {
		public Type_fieldsContext type_fields() {
			return GetRuleContext<Type_fieldsContext>(0);
		}
		public RecordTypeContext(TypeContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRecordType(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdTypeContext : TypeContext {
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public IdTypeContext(TypeContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 8, RULE_type);
		int _la;
		try {
			State = 190;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				_localctx = new IdTypeContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 181; Match(ID);
				}
				break;
			case T__18:
				_localctx = new RecordTypeContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 182; Match(T__18);
				State = 184;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ID) {
					{
					State = 183; type_fields();
					}
				}

				State = 186; Match(T__19);
				}
				break;
			case T__39:
				_localctx = new ArrayTypeContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 187; Match(T__39);
				State = 188; Match(T__22);
				State = 189; Match(ID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_fieldsContext : ParserRuleContext {
		public Type_fieldsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_fields; } }
	 
		public Type_fieldsContext() { }
		public virtual void CopyFrom(Type_fieldsContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class TypeFieldsContext : Type_fieldsContext {
		public ITerminalNode[] ID() { return GetTokens(TigerParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(TigerParser.ID, i);
		}
		public TypeFieldsContext(Type_fieldsContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeFields(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_fieldsContext type_fields() {
		Type_fieldsContext _localctx = new Type_fieldsContext(Context, State);
		EnterRule(_localctx, 10, RULE_type_fields);
		int _la;
		try {
			_localctx = new TypeFieldsContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 192; Match(ID);
			State = 193; Match(T__37);
			State = 194; Match(ID);
			State = 201;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__15) {
				{
				{
				State = 195; Match(T__15);
				State = 196; Match(ID);
				State = 197; Match(T__37);
				State = 198; Match(ID);
				}
				}
				State = 203;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 1: return expr_sempred((ExprContext)_localctx, predIndex);
		case 2: return lvalue_sempred((LvalueContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 15);
		case 1: return Precpred(Context, 14);
		case 2: return Precpred(Context, 13);
		case 3: return Precpred(Context, 12);
		case 4: return Precpred(Context, 11);
		}
		return true;
	}
	private bool lvalue_sempred(LvalueContext _localctx, int predIndex) {
		switch (predIndex) {
		case 5: return Precpred(Context, 2);
		case 6: return Precpred(Context, 1);
		}
		return true;
	}

	private static string _serializedATN = _serializeATN();
	private static string _serializeATN()
	{
	    StringBuilder sb = new StringBuilder();
	    sb.Append("\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x3/\xCF");
		sb.Append("\x4\x2\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a");
		sb.Append("\t\a\x3\x2\x3\x2\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\a\x3!\n");
		sb.Append("\x3\f\x3\xE\x3$\v\x3\x5\x3&\n\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\x3\a\x3-\n\x3\f\x3\xE\x3\x30\v\x3\x5\x3\x32\n\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\a\x3>\n\x3");
		sb.Append("\f\x3\xE\x3\x41\v\x3\x5\x3\x43\n\x3\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\x5\x3S\n\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\a\x3");
		sb.Append("\x66\n\x3\f\x3\xE\x3i\v\x3\x3\x3\x3\x3\x3\x3\x3\x3\a\x3o\n\x3");
		sb.Append("\f\x3\xE\x3r\v\x3\x5\x3t\n\x3\x3\x3\x5\x3w\n\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\x3\x3\x3\x3\a\x3\x88\n\x3\f\x3\xE\x3\x8B\v\x3\x3\x4\x3");
		sb.Append("\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\a");
		sb.Append("\x4\x98\n\x4\f\x4\xE\x4\x9B\v\x4\x3\x5\x3\x5\x3\x5\x3\x5\x3");
		sb.Append("\x5\x3\x5\x3\x5\x3\x5\x5\x5\xA5\n\x5\x3\x5\x3\x5\x3\x5\x3\x5");
		sb.Append("\x3\x5\x3\x5\x5\x5\xAD\n\x5\x3\x5\x3\x5\x3\x5\x5\x5\xB2\n\x5");
		sb.Append("\x3\x5\x3\x5\x5\x5\xB6\n\x5\x3\x6\x3\x6\x3\x6\x5\x6\xBB\n\x6");
		sb.Append("\x3\x6\x3\x6\x3\x6\x3\x6\x5\x6\xC1\n\x6\x3\a\x3\a\x3\a\x3\a");
		sb.Append("\x3\a\x3\a\x3\a\a\a\xCA\n\a\f\a\xE\a\xCD\v\a\x3\a\x2\x4\x4\x6");
		sb.Append("\b\x2\x4\x6\b\n\f\x2\x5\x3\x2\x5\x6\x4\x2\x4\x4\a\a\x3\x2\b");
		sb.Append("\r\xF0\x2\xE\x3\x2\x2\x2\x4v\x3\x2\x2\x2\x6\x8C\x3\x2\x2\x2");
		sb.Append("\b\xB5\x3\x2\x2\x2\n\xC0\x3\x2\x2\x2\f\xC2\x3\x2\x2\x2\xE\xF");
		sb.Append("\x5\x4\x3\x2\xF\x3\x3\x2\x2\x2\x10\x11\b\x3\x1\x2\x11w\a,\x2");
		sb.Append("\x2\x12w\a-\x2\x2\x13w\a\x3\x2\x2\x14w\x5\x6\x4\x2\x15\x16\a");
		sb.Append("\x4\x2\x2\x16w\x5\x4\x3\x12\x17\x18\x5\x6\x4\x2\x18\x19\a\x10");
		sb.Append("\x2\x2\x19\x1A\x5\x4\x3\f\x1Aw\x3\x2\x2\x2\x1B\x1C\a.\x2\x2");
		sb.Append("\x1C%\a\x11\x2\x2\x1D\"\x5\x4\x3\x2\x1E\x1F\a\x12\x2\x2\x1F");
		sb.Append("!\x5\x4\x3\x2 \x1E\x3\x2\x2\x2!$\x3\x2\x2\x2\" \x3\x2\x2\x2");
		sb.Append("\"#\x3\x2\x2\x2#&\x3\x2\x2\x2$\"\x3\x2\x2\x2%\x1D\x3\x2\x2\x2");
		sb.Append("%&\x3\x2\x2\x2&\'\x3\x2\x2\x2\'w\a\x13\x2\x2(\x31\a\x11\x2\x2");
		sb.Append(").\x5\x4\x3\x2*+\a\x14\x2\x2+-\x5\x4\x3\x2,*\x3\x2\x2\x2-\x30");
		sb.Append("\x3\x2\x2\x2.,\x3\x2\x2\x2./\x3\x2\x2\x2/\x32\x3\x2\x2\x2\x30");
		sb.Append(".\x3\x2\x2\x2\x31)\x3\x2\x2\x2\x31\x32\x3\x2\x2\x2\x32\x33\x3");
		sb.Append("\x2\x2\x2\x33w\a\x13\x2\x2\x34\x35\a.\x2\x2\x35\x42\a\x15\x2");
		sb.Append("\x2\x36\x37\a.\x2\x2\x37\x38\a\t\x2\x2\x38?\x5\x4\x3\x2\x39");
		sb.Append(":\a\x12\x2\x2:;\a.\x2\x2;<\a\t\x2\x2<>\x5\x4\x3\x2=\x39\x3\x2");
		sb.Append("\x2\x2>\x41\x3\x2\x2\x2?=\x3\x2\x2\x2?@\x3\x2\x2\x2@\x43\x3");
		sb.Append("\x2\x2\x2\x41?\x3\x2\x2\x2\x42\x36\x3\x2\x2\x2\x42\x43\x3\x2");
		sb.Append("\x2\x2\x43\x44\x3\x2\x2\x2\x44w\a\x16\x2\x2\x45\x46\a.\x2\x2");
		sb.Append("\x46G\a\x17\x2\x2GH\x5\x4\x3\x2HI\a\x18\x2\x2IJ\a\x19\x2\x2");
		sb.Append("JK\x5\x4\x3\bKw\x3\x2\x2\x2LM\a\x1A\x2\x2MN\x5\x4\x3\x2NO\a");
		sb.Append("\x1B\x2\x2OR\x5\x4\x3\x2PQ\a\x1C\x2\x2QS\x5\x4\x3\x2RP\x3\x2");
		sb.Append("\x2\x2RS\x3\x2\x2\x2Sw\x3\x2\x2\x2TU\a\x1D\x2\x2UV\x5\x4\x3");
		sb.Append("\x2VW\a\x1E\x2\x2WX\x5\x4\x3\x6Xw\x3\x2\x2\x2YZ\a\x1F\x2\x2");
		sb.Append("Z[\a.\x2\x2[\\\a\x10\x2\x2\\]\x5\x4\x3\x2]^\a \x2\x2^_\x5\x4");
		sb.Append("\x3\x2_`\a\x1E\x2\x2`\x61\x5\x4\x3\x5\x61w\x3\x2\x2\x2\x62w");
		sb.Append("\a!\x2\x2\x63g\a\"\x2\x2\x64\x66\x5\b\x5\x2\x65\x64\x3\x2\x2");
		sb.Append("\x2\x66i\x3\x2\x2\x2g\x65\x3\x2\x2\x2gh\x3\x2\x2\x2hj\x3\x2");
		sb.Append("\x2\x2ig\x3\x2\x2\x2js\a#\x2\x2kp\x5\x4\x3\x2lm\a\x14\x2\x2");
		sb.Append("mo\x5\x4\x3\x2nl\x3\x2\x2\x2or\x3\x2\x2\x2pn\x3\x2\x2\x2pq\x3");
		sb.Append("\x2\x2\x2qt\x3\x2\x2\x2rp\x3\x2\x2\x2sk\x3\x2\x2\x2st\x3\x2");
		sb.Append("\x2\x2tu\x3\x2\x2\x2uw\a$\x2\x2v\x10\x3\x2\x2\x2v\x12\x3\x2");
		sb.Append("\x2\x2v\x13\x3\x2\x2\x2v\x14\x3\x2\x2\x2v\x15\x3\x2\x2\x2v\x17");
		sb.Append("\x3\x2\x2\x2v\x1B\x3\x2\x2\x2v(\x3\x2\x2\x2v\x34\x3\x2\x2\x2");
		sb.Append("v\x45\x3\x2\x2\x2vL\x3\x2\x2\x2vT\x3\x2\x2\x2vY\x3\x2\x2\x2");
		sb.Append("v\x62\x3\x2\x2\x2v\x63\x3\x2\x2\x2w\x89\x3\x2\x2\x2xy\f\x11");
		sb.Append("\x2\x2yz\t\x2\x2\x2z\x88\x5\x4\x3\x12{|\f\x10\x2\x2|}\t\x3\x2");
		sb.Append("\x2}\x88\x5\x4\x3\x11~\x7F\f\xF\x2\x2\x7F\x80\t\x4\x2\x2\x80");
		sb.Append("\x88\x5\x4\x3\x10\x81\x82\f\xE\x2\x2\x82\x83\a\xE\x2\x2\x83");
		sb.Append("\x88\x5\x4\x3\xF\x84\x85\f\r\x2\x2\x85\x86\a\xF\x2\x2\x86\x88");
		sb.Append("\x5\x4\x3\xE\x87x\x3\x2\x2\x2\x87{\x3\x2\x2\x2\x87~\x3\x2\x2");
		sb.Append("\x2\x87\x81\x3\x2\x2\x2\x87\x84\x3\x2\x2\x2\x88\x8B\x3\x2\x2");
		sb.Append("\x2\x89\x87\x3\x2\x2\x2\x89\x8A\x3\x2\x2\x2\x8A\x5\x3\x2\x2");
		sb.Append("\x2\x8B\x89\x3\x2\x2\x2\x8C\x8D\b\x4\x1\x2\x8D\x8E\a.\x2\x2");
		sb.Append("\x8E\x99\x3\x2\x2\x2\x8F\x90\f\x4\x2\x2\x90\x91\a%\x2\x2\x91");
		sb.Append("\x98\a.\x2\x2\x92\x93\f\x3\x2\x2\x93\x94\a\x17\x2\x2\x94\x95");
		sb.Append("\x5\x4\x3\x2\x95\x96\a\x18\x2\x2\x96\x98\x3\x2\x2\x2\x97\x8F");
		sb.Append("\x3\x2\x2\x2\x97\x92\x3\x2\x2\x2\x98\x9B\x3\x2\x2\x2\x99\x97");
		sb.Append("\x3\x2\x2\x2\x99\x9A\x3\x2\x2\x2\x9A\a\x3\x2\x2\x2\x9B\x99\x3");
		sb.Append("\x2\x2\x2\x9C\x9D\a&\x2\x2\x9D\x9E\a.\x2\x2\x9E\x9F\a\t\x2\x2");
		sb.Append("\x9F\xB6\x5\n\x6\x2\xA0\xA1\a\'\x2\x2\xA1\xA4\a.\x2\x2\xA2\xA3");
		sb.Append("\a(\x2\x2\xA3\xA5\a.\x2\x2\xA4\xA2\x3\x2\x2\x2\xA4\xA5\x3\x2");
		sb.Append("\x2\x2\xA5\xA6\x3\x2\x2\x2\xA6\xA7\a\x10\x2\x2\xA7\xB6\x5\x4");
		sb.Append("\x3\x2\xA8\xA9\a)\x2\x2\xA9\xAA\a.\x2\x2\xAA\xAC\a\x11\x2\x2");
		sb.Append("\xAB\xAD\x5\f\a\x2\xAC\xAB\x3\x2\x2\x2\xAC\xAD\x3\x2\x2\x2\xAD");
		sb.Append("\xAE\x3\x2\x2\x2\xAE\xB1\a\x13\x2\x2\xAF\xB0\a(\x2\x2\xB0\xB2");
		sb.Append("\a.\x2\x2\xB1\xAF\x3\x2\x2\x2\xB1\xB2\x3\x2\x2\x2\xB2\xB3\x3");
		sb.Append("\x2\x2\x2\xB3\xB4\a\t\x2\x2\xB4\xB6\x5\x4\x3\x2\xB5\x9C\x3\x2");
		sb.Append("\x2\x2\xB5\xA0\x3\x2\x2\x2\xB5\xA8\x3\x2\x2\x2\xB6\t\x3\x2\x2");
		sb.Append("\x2\xB7\xC1\a.\x2\x2\xB8\xBA\a\x15\x2\x2\xB9\xBB\x5\f\a\x2\xBA");
		sb.Append("\xB9\x3\x2\x2\x2\xBA\xBB\x3\x2\x2\x2\xBB\xBC\x3\x2\x2\x2\xBC");
		sb.Append("\xC1\a\x16\x2\x2\xBD\xBE\a*\x2\x2\xBE\xBF\a\x19\x2\x2\xBF\xC1");
		sb.Append("\a.\x2\x2\xC0\xB7\x3\x2\x2\x2\xC0\xB8\x3\x2\x2\x2\xC0\xBD\x3");
		sb.Append("\x2\x2\x2\xC1\v\x3\x2\x2\x2\xC2\xC3\a.\x2\x2\xC3\xC4\a(\x2\x2");
		sb.Append("\xC4\xCB\a.\x2\x2\xC5\xC6\a\x12\x2\x2\xC6\xC7\a.\x2\x2\xC7\xC8");
		sb.Append("\a(\x2\x2\xC8\xCA\a.\x2\x2\xC9\xC5\x3\x2\x2\x2\xCA\xCD\x3\x2");
		sb.Append("\x2\x2\xCB\xC9\x3\x2\x2\x2\xCB\xCC\x3\x2\x2\x2\xCC\r\x3\x2\x2");
		sb.Append("\x2\xCD\xCB\x3\x2\x2\x2\x18\"%.\x31?\x42Rgpsv\x87\x89\x97\x99");
		sb.Append("\xA4\xAC\xB1\xB5\xBA\xC0\xCB");
	    return sb.ToString();
	}

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());


}
