//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\Zchool\Computer Science\4º\VII Semestre\Complementos de Compilación\Tiger\Tiger\Parsing\Tiger.g4 by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public partial class TigerParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, STRING=41, INTEGER=42, ID=43, COMMENT=44, WS=45;
	public const int
		RULE_compileUnit = 0, RULE_expr = 1, RULE_lvalue = 2, RULE_decls = 3, 
		RULE_func_decl = 4, RULE_type = 5, RULE_type_fields = 6;
	public static readonly string[] ruleNames = {
		"compileUnit", "expr", "lvalue", "decls", "func_decl", "type", "type_fields"
	};

	private static readonly string[] _LiteralNames = {
		null, "'nil'", "'-'", "'*'", "'/'", "'+'", "'<>'", "'='", "'>='", "'<='", 
		"'>'", "'<'", "'&'", "'|'", "':='", "'('", "','", "')'", "';'", "'{'", 
		"'}'", "'['", "']'", "'of'", "'if'", "'then'", "'else'", "'while'", "'do'", 
		"'for'", "'to'", "'break'", "'let'", "'in'", "'end'", "'.'", "'type'", 
		"'var'", "':'", "'function'", "'array'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, "STRING", "INTEGER", "ID", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Tiger.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	static TigerParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

	public TigerParser(ITokenStream input)
		: base(input)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class CompileUnitContext : ParserRuleContext {
		public CompileUnitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compileUnit; } }
	 
		public CompileUnitContext() { }
		public virtual void CopyFrom(CompileUnitContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ProgramContext : CompileUnitContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(TigerParser.Eof, 0); }
		public ProgramContext(CompileUnitContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CompileUnitContext compileUnit() {
		CompileUnitContext _localctx = new CompileUnitContext(Context, State);
		EnterRule(_localctx, 0, RULE_compileUnit);
		try {
			_localctx = new ProgramContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 14; expr(0);
			State = 15; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class CallContext : ExprContext {
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public CallContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCall(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParenExprsContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ParenExprsContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenExprs(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ForContext : ExprContext {
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ForContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFor(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BreakContext : ExprContext {
		public BreakContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBreak(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LogicalContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public LogicalContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogical(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryMinusContext : ExprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public UnaryMinusContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryMinus(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StringContext : ExprContext {
		public ITerminalNode STRING() { return GetToken(TigerParser.STRING, 0); }
		public StringContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class WhileContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public WhileContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhile(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntegerContext : ExprContext {
		public ITerminalNode INTEGER() { return GetToken(TigerParser.INTEGER, 0); }
		public IntegerContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInteger(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NilContext : ExprContext {
		public NilContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNil(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ArrayContext : ExprContext {
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ArrayContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArray(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ComparisonContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ComparisonContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComparison(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AssignContext : ExprContext {
		public LvalueContext lvalue() {
			return GetRuleContext<LvalueContext>(0);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public AssignContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssign(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RecordContext : ExprContext {
		public IToken typeID;
		public ITerminalNode[] ID() { return GetTokens(TigerParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(TigerParser.ID, i);
		}
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public RecordContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRecord(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LetContext : ExprContext {
		public DeclsContext[] decls() {
			return GetRuleContexts<DeclsContext>();
		}
		public DeclsContext decls(int i) {
			return GetRuleContext<DeclsContext>(i);
		}
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public LetContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLet(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LValueContext : ExprContext {
		public LvalueContext lvalue() {
			return GetRuleContext<LvalueContext>(0);
		}
		public LValueContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IfContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public IfContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIf(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ArithmeticContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ArithmeticContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArithmetic(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 2;
		EnterRecursionRule(_localctx, 2, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 119;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				{
				_localctx = new StringContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 18; Match(STRING);
				}
				break;
			case 2:
				{
				_localctx = new IntegerContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 19; Match(INTEGER);
				}
				break;
			case 3:
				{
				_localctx = new NilContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 20; Match(T__0);
				}
				break;
			case 4:
				{
				_localctx = new LValueContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 21; lvalue(0);
				}
				break;
			case 5:
				{
				_localctx = new UnaryMinusContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 22; Match(T__1);
				State = 23; expr(16);
				}
				break;
			case 6:
				{
				_localctx = new AssignContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 24; lvalue(0);
				State = 25; Match(T__13);
				State = 26; expr(10);
				}
				break;
			case 7:
				{
				_localctx = new CallContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 28; Match(ID);
				State = 29; Match(T__14);
				State = 38;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__14) | (1L << T__23) | (1L << T__26) | (1L << T__28) | (1L << T__30) | (1L << T__31) | (1L << STRING) | (1L << INTEGER) | (1L << ID))) != 0)) {
					{
					State = 30; expr(0);
					State = 35;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__15) {
						{
						{
						State = 31; Match(T__15);
						State = 32; expr(0);
						}
						}
						State = 37;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 40; Match(T__16);
				}
				break;
			case 8:
				{
				_localctx = new ParenExprsContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 41; Match(T__14);
				State = 50;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__14) | (1L << T__23) | (1L << T__26) | (1L << T__28) | (1L << T__30) | (1L << T__31) | (1L << STRING) | (1L << INTEGER) | (1L << ID))) != 0)) {
					{
					State = 42; expr(0);
					State = 47;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__17) {
						{
						{
						State = 43; Match(T__17);
						State = 44; expr(0);
						}
						}
						State = 49;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 52; Match(T__16);
				}
				break;
			case 9:
				{
				_localctx = new RecordContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 53; ((RecordContext)_localctx).typeID = Match(ID);
				State = 54; Match(T__18);
				State = 67;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ID) {
					{
					State = 55; Match(ID);
					State = 56; Match(T__6);
					State = 57; expr(0);
					State = 64;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__15) {
						{
						{
						State = 58; Match(T__15);
						State = 59; Match(ID);
						State = 60; Match(T__6);
						State = 61; expr(0);
						}
						}
						State = 66;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 69; Match(T__19);
				}
				break;
			case 10:
				{
				_localctx = new ArrayContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 70; Match(ID);
				State = 71; Match(T__20);
				State = 72; expr(0);
				State = 73; Match(T__21);
				State = 74; Match(T__22);
				State = 75; expr(6);
				}
				break;
			case 11:
				{
				_localctx = new IfContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 77; Match(T__23);
				State = 78; expr(0);
				State = 79; Match(T__24);
				State = 80; expr(0);
				State = 83;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
				case 1:
					{
					State = 81; Match(T__25);
					State = 82; expr(0);
					}
					break;
				}
				}
				break;
			case 12:
				{
				_localctx = new WhileContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 85; Match(T__26);
				State = 86; expr(0);
				State = 87; Match(T__27);
				State = 88; expr(4);
				}
				break;
			case 13:
				{
				_localctx = new ForContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 90; Match(T__28);
				State = 91; Match(ID);
				State = 92; Match(T__13);
				State = 93; expr(0);
				State = 94; Match(T__29);
				State = 95; expr(0);
				State = 96; Match(T__27);
				State = 97; expr(3);
				}
				break;
			case 14:
				{
				_localctx = new BreakContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 99; Match(T__30);
				}
				break;
			case 15:
				{
				_localctx = new LetContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 100; Match(T__31);
				State = 102;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 101; decls();
					}
					}
					State = 104;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__35) | (1L << T__36) | (1L << T__38))) != 0) );
				State = 106; Match(T__32);
				State = 115;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__14) | (1L << T__23) | (1L << T__26) | (1L << T__28) | (1L << T__30) | (1L << T__31) | (1L << STRING) | (1L << INTEGER) | (1L << ID))) != 0)) {
					{
					State = 107; expr(0);
					State = 112;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__17) {
						{
						{
						State = 108; Match(T__17);
						State = 109; expr(0);
						}
						}
						State = 114;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 117; Match(T__33);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 138;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 136;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
					case 1:
						{
						_localctx = new ArithmeticContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 121;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 122;
						((ArithmeticContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==T__2 || _la==T__3) ) {
							((ArithmeticContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 123; expr(16);
						}
						break;
					case 2:
						{
						_localctx = new ArithmeticContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 124;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 125;
						((ArithmeticContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==T__1 || _la==T__4) ) {
							((ArithmeticContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 126; expr(15);
						}
						break;
					case 3:
						{
						_localctx = new ComparisonContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 127;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 128;
						((ComparisonContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__5) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << T__10))) != 0)) ) {
							((ComparisonContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 129; expr(14);
						}
						break;
					case 4:
						{
						_localctx = new LogicalContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 130;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 131; ((LogicalContext)_localctx).op = Match(T__11);
						State = 132; expr(13);
						}
						break;
					case 5:
						{
						_localctx = new LogicalContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 133;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 134; ((LogicalContext)_localctx).op = Match(T__12);
						State = 135; expr(12);
						}
						break;
					}
					} 
				}
				State = 140;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class LvalueContext : ParserRuleContext {
		public LvalueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_lvalue; } }
	 
		public LvalueContext() { }
		public virtual void CopyFrom(LvalueContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class IndexLValueContext : LvalueContext {
		public LvalueContext lvalue() {
			return GetRuleContext<LvalueContext>(0);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public IndexLValueContext(LvalueContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIndexLValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdLValueContext : LvalueContext {
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public IdLValueContext(LvalueContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdLValue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FieldLValueContext : LvalueContext {
		public LvalueContext lvalue() {
			return GetRuleContext<LvalueContext>(0);
		}
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public FieldLValueContext(LvalueContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFieldLValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LvalueContext lvalue() {
		return lvalue(0);
	}

	private LvalueContext lvalue(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		LvalueContext _localctx = new LvalueContext(Context, _parentState);
		LvalueContext _prevctx = _localctx;
		int _startState = 4;
		EnterRecursionRule(_localctx, 4, RULE_lvalue, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			_localctx = new IdLValueContext(_localctx);
			Context = _localctx;
			_prevctx = _localctx;

			State = 142; Match(ID);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 154;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 152;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
					case 1:
						{
						_localctx = new FieldLValueContext(new LvalueContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_lvalue);
						State = 144;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 145; Match(T__34);
						State = 146; Match(ID);
						}
						break;
					case 2:
						{
						_localctx = new IndexLValueContext(new LvalueContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_lvalue);
						State = 147;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 148; Match(T__20);
						State = 149; expr(0);
						State = 150; Match(T__21);
						}
						break;
					}
					} 
				}
				State = 156;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class DeclsContext : ParserRuleContext {
		public DeclsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_decls; } }
	 
		public DeclsContext() { }
		public virtual void CopyFrom(DeclsContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class VarDeclContext : DeclsContext {
		public IToken id;
		public IToken typeId;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode[] ID() { return GetTokens(TigerParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(TigerParser.ID, i);
		}
		public VarDeclContext(DeclsContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVarDecl(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class TypeDeclsContext : DeclsContext {
		public ITerminalNode[] ID() { return GetTokens(TigerParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(TigerParser.ID, i);
		}
		public TypeContext[] type() {
			return GetRuleContexts<TypeContext>();
		}
		public TypeContext type(int i) {
			return GetRuleContext<TypeContext>(i);
		}
		public TypeDeclsContext(DeclsContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeDecls(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncDeclsContext : DeclsContext {
		public Func_declContext[] func_decl() {
			return GetRuleContexts<Func_declContext>();
		}
		public Func_declContext func_decl(int i) {
			return GetRuleContext<Func_declContext>(i);
		}
		public FuncDeclsContext(DeclsContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncDecls(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeclsContext decls() {
		DeclsContext _localctx = new DeclsContext(Context, State);
		EnterRule(_localctx, 6, RULE_decls);
		int _la;
		try {
			int _alt;
			State = 178;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__35:
				_localctx = new TypeDeclsContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 161;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 157; Match(T__35);
						State = 158; Match(ID);
						State = 159; Match(T__6);
						State = 160; type();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 163;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				}
				break;
			case T__36:
				_localctx = new VarDeclContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 165; Match(T__36);
				State = 166; ((VarDeclContext)_localctx).id = Match(ID);
				State = 169;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__37) {
					{
					State = 167; Match(T__37);
					State = 168; ((VarDeclContext)_localctx).typeId = Match(ID);
					}
				}

				State = 171; Match(T__13);
				State = 172; expr(0);
				}
				break;
			case T__38:
				_localctx = new FuncDeclsContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 174;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 173; func_decl();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 176;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_declContext : ParserRuleContext {
		public Func_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_decl; } }
	 
		public Func_declContext() { }
		public virtual void CopyFrom(Func_declContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class FuncDeclContext : Func_declContext {
		public IToken id;
		public IToken typeId;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode[] ID() { return GetTokens(TigerParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(TigerParser.ID, i);
		}
		public Type_fieldsContext type_fields() {
			return GetRuleContext<Type_fieldsContext>(0);
		}
		public FuncDeclContext(Func_declContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncDecl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Func_declContext func_decl() {
		Func_declContext _localctx = new Func_declContext(Context, State);
		EnterRule(_localctx, 8, RULE_func_decl);
		int _la;
		try {
			_localctx = new FuncDeclContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 180; Match(T__38);
			State = 181; ((FuncDeclContext)_localctx).id = Match(ID);
			State = 182; Match(T__14);
			State = 184;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 183; type_fields();
				}
			}

			State = 186; Match(T__16);
			State = 189;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__37) {
				{
				State = 187; Match(T__37);
				State = 188; ((FuncDeclContext)_localctx).typeId = Match(ID);
				}
			}

			State = 191; Match(T__6);
			State = 192; expr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
	 
		public TypeContext() { }
		public virtual void CopyFrom(TypeContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ArrayTypeContext : TypeContext {
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public ArrayTypeContext(TypeContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayType(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RecordTypeContext : TypeContext {
		public Type_fieldsContext type_fields() {
			return GetRuleContext<Type_fieldsContext>(0);
		}
		public RecordTypeContext(TypeContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRecordType(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdTypeContext : TypeContext {
		public ITerminalNode ID() { return GetToken(TigerParser.ID, 0); }
		public IdTypeContext(TypeContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 10, RULE_type);
		int _la;
		try {
			State = 203;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				_localctx = new IdTypeContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 194; Match(ID);
				}
				break;
			case T__18:
				_localctx = new RecordTypeContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 195; Match(T__18);
				State = 197;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ID) {
					{
					State = 196; type_fields();
					}
				}

				State = 199; Match(T__19);
				}
				break;
			case T__39:
				_localctx = new ArrayTypeContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 200; Match(T__39);
				State = 201; Match(T__22);
				State = 202; Match(ID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_fieldsContext : ParserRuleContext {
		public Type_fieldsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_fields; } }
	 
		public Type_fieldsContext() { }
		public virtual void CopyFrom(Type_fieldsContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class TypeFieldsContext : Type_fieldsContext {
		public ITerminalNode[] ID() { return GetTokens(TigerParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(TigerParser.ID, i);
		}
		public TypeFieldsContext(Type_fieldsContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITigerVisitor<TResult> typedVisitor = visitor as ITigerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeFields(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_fieldsContext type_fields() {
		Type_fieldsContext _localctx = new Type_fieldsContext(Context, State);
		EnterRule(_localctx, 12, RULE_type_fields);
		int _la;
		try {
			_localctx = new TypeFieldsContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 205; Match(ID);
			State = 206; Match(T__37);
			State = 207; Match(ID);
			State = 214;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__15) {
				{
				{
				State = 208; Match(T__15);
				State = 209; Match(ID);
				State = 210; Match(T__37);
				State = 211; Match(ID);
				}
				}
				State = 216;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 1: return expr_sempred((ExprContext)_localctx, predIndex);
		case 2: return lvalue_sempred((LvalueContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 15);
		case 1: return Precpred(Context, 14);
		case 2: return Precpred(Context, 13);
		case 3: return Precpred(Context, 12);
		case 4: return Precpred(Context, 11);
		}
		return true;
	}
	private bool lvalue_sempred(LvalueContext _localctx, int predIndex) {
		switch (predIndex) {
		case 5: return Precpred(Context, 2);
		case 6: return Precpred(Context, 1);
		}
		return true;
	}

	private static string _serializedATN = _serializeATN();
	private static string _serializeATN()
	{
	    StringBuilder sb = new StringBuilder();
	    sb.Append("\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x3/\xDC");
		sb.Append("\x4\x2\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a");
		sb.Append("\t\a\x4\b\t\b\x3\x2\x3\x2\x3\x2\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\a\x3$\n\x3\f\x3\xE\x3\'\v\x3\x5\x3)\n\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\x3\x3\x3\x3\a\x3\x30\n\x3\f\x3\xE\x3\x33\v\x3\x5\x3\x35");
		sb.Append("\n\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\a\x3\x41\n\x3\f\x3\xE\x3\x44\v\x3\x5\x3\x46\n\x3\x3\x3");
		sb.Append("\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\x3\x3\x3\x3\x5\x3V\n\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\x3\x3\x6\x3i\n\x3\r\x3\xE\x3j\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\a\x3q\n\x3\f\x3\xE\x3t\v\x3\x5\x3v\n\x3\x3\x3\x3\x3\x5\x3z");
		sb.Append("\n\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3");
		sb.Append("\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\a\x3\x8B\n\x3\f\x3\xE\x3");
		sb.Append("\x8E\v\x3\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3");
		sb.Append("\x4\x3\x4\x3\x4\a\x4\x9B\n\x4\f\x4\xE\x4\x9E\v\x4\x3\x5\x3\x5");
		sb.Append("\x3\x5\x3\x5\x6\x5\xA4\n\x5\r\x5\xE\x5\xA5\x3\x5\x3\x5\x3\x5");
		sb.Append("\x3\x5\x5\x5\xAC\n\x5\x3\x5\x3\x5\x3\x5\x6\x5\xB1\n\x5\r\x5");
		sb.Append("\xE\x5\xB2\x5\x5\xB5\n\x5\x3\x6\x3\x6\x3\x6\x3\x6\x5\x6\xBB");
		sb.Append("\n\x6\x3\x6\x3\x6\x3\x6\x5\x6\xC0\n\x6\x3\x6\x3\x6\x3\x6\x3");
		sb.Append("\a\x3\a\x3\a\x5\a\xC8\n\a\x3\a\x3\a\x3\a\x3\a\x5\a\xCE\n\a\x3");
		sb.Append("\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\a\b\xD7\n\b\f\b\xE\b\xDA\v");
		sb.Append("\b\x3\b\x2\x4\x4\x6\t\x2\x4\x6\b\n\f\xE\x2\x5\x3\x2\x5\x6\x4");
		sb.Append("\x2\x4\x4\a\a\x3\x2\b\r\xFE\x2\x10\x3\x2\x2\x2\x4y\x3\x2\x2");
		sb.Append("\x2\x6\x8F\x3\x2\x2\x2\b\xB4\x3\x2\x2\x2\n\xB6\x3\x2\x2\x2\f");
		sb.Append("\xCD\x3\x2\x2\x2\xE\xCF\x3\x2\x2\x2\x10\x11\x5\x4\x3\x2\x11");
		sb.Append("\x12\a\x2\x2\x3\x12\x3\x3\x2\x2\x2\x13\x14\b\x3\x1\x2\x14z\a");
		sb.Append("+\x2\x2\x15z\a,\x2\x2\x16z\a\x3\x2\x2\x17z\x5\x6\x4\x2\x18\x19");
		sb.Append("\a\x4\x2\x2\x19z\x5\x4\x3\x12\x1A\x1B\x5\x6\x4\x2\x1B\x1C\a");
		sb.Append("\x10\x2\x2\x1C\x1D\x5\x4\x3\f\x1Dz\x3\x2\x2\x2\x1E\x1F\a-\x2");
		sb.Append("\x2\x1F(\a\x11\x2\x2 %\x5\x4\x3\x2!\"\a\x12\x2\x2\"$\x5\x4\x3");
		sb.Append("\x2#!\x3\x2\x2\x2$\'\x3\x2\x2\x2%#\x3\x2\x2\x2%&\x3\x2\x2\x2");
		sb.Append("&)\x3\x2\x2\x2\'%\x3\x2\x2\x2( \x3\x2\x2\x2()\x3\x2\x2\x2)*");
		sb.Append("\x3\x2\x2\x2*z\a\x13\x2\x2+\x34\a\x11\x2\x2,\x31\x5\x4\x3\x2");
		sb.Append("-.\a\x14\x2\x2.\x30\x5\x4\x3\x2/-\x3\x2\x2\x2\x30\x33\x3\x2");
		sb.Append("\x2\x2\x31/\x3\x2\x2\x2\x31\x32\x3\x2\x2\x2\x32\x35\x3\x2\x2");
		sb.Append("\x2\x33\x31\x3\x2\x2\x2\x34,\x3\x2\x2\x2\x34\x35\x3\x2\x2\x2");
		sb.Append("\x35\x36\x3\x2\x2\x2\x36z\a\x13\x2\x2\x37\x38\a-\x2\x2\x38\x45");
		sb.Append("\a\x15\x2\x2\x39:\a-\x2\x2:;\a\t\x2\x2;\x42\x5\x4\x3\x2<=\a");
		sb.Append("\x12\x2\x2=>\a-\x2\x2>?\a\t\x2\x2?\x41\x5\x4\x3\x2@<\x3\x2\x2");
		sb.Append("\x2\x41\x44\x3\x2\x2\x2\x42@\x3\x2\x2\x2\x42\x43\x3\x2\x2\x2");
		sb.Append("\x43\x46\x3\x2\x2\x2\x44\x42\x3\x2\x2\x2\x45\x39\x3\x2\x2\x2");
		sb.Append("\x45\x46\x3\x2\x2\x2\x46G\x3\x2\x2\x2Gz\a\x16\x2\x2HI\a-\x2");
		sb.Append("\x2IJ\a\x17\x2\x2JK\x5\x4\x3\x2KL\a\x18\x2\x2LM\a\x19\x2\x2");
		sb.Append("MN\x5\x4\x3\bNz\x3\x2\x2\x2OP\a\x1A\x2\x2PQ\x5\x4\x3\x2QR\a");
		sb.Append("\x1B\x2\x2RU\x5\x4\x3\x2ST\a\x1C\x2\x2TV\x5\x4\x3\x2US\x3\x2");
		sb.Append("\x2\x2UV\x3\x2\x2\x2Vz\x3\x2\x2\x2WX\a\x1D\x2\x2XY\x5\x4\x3");
		sb.Append("\x2YZ\a\x1E\x2\x2Z[\x5\x4\x3\x6[z\x3\x2\x2\x2\\]\a\x1F\x2\x2");
		sb.Append("]^\a-\x2\x2^_\a\x10\x2\x2_`\x5\x4\x3\x2`\x61\a \x2\x2\x61\x62");
		sb.Append("\x5\x4\x3\x2\x62\x63\a\x1E\x2\x2\x63\x64\x5\x4\x3\x5\x64z\x3");
		sb.Append("\x2\x2\x2\x65z\a!\x2\x2\x66h\a\"\x2\x2gi\x5\b\x5\x2hg\x3\x2");
		sb.Append("\x2\x2ij\x3\x2\x2\x2jh\x3\x2\x2\x2jk\x3\x2\x2\x2kl\x3\x2\x2");
		sb.Append("\x2lu\a#\x2\x2mr\x5\x4\x3\x2no\a\x14\x2\x2oq\x5\x4\x3\x2pn\x3");
		sb.Append("\x2\x2\x2qt\x3\x2\x2\x2rp\x3\x2\x2\x2rs\x3\x2\x2\x2sv\x3\x2");
		sb.Append("\x2\x2tr\x3\x2\x2\x2um\x3\x2\x2\x2uv\x3\x2\x2\x2vw\x3\x2\x2");
		sb.Append("\x2wx\a$\x2\x2xz\x3\x2\x2\x2y\x13\x3\x2\x2\x2y\x15\x3\x2\x2");
		sb.Append("\x2y\x16\x3\x2\x2\x2y\x17\x3\x2\x2\x2y\x18\x3\x2\x2\x2y\x1A");
		sb.Append("\x3\x2\x2\x2y\x1E\x3\x2\x2\x2y+\x3\x2\x2\x2y\x37\x3\x2\x2\x2");
		sb.Append("yH\x3\x2\x2\x2yO\x3\x2\x2\x2yW\x3\x2\x2\x2y\\\x3\x2\x2\x2y\x65");
		sb.Append("\x3\x2\x2\x2y\x66\x3\x2\x2\x2z\x8C\x3\x2\x2\x2{|\f\x11\x2\x2");
		sb.Append("|}\t\x2\x2\x2}\x8B\x5\x4\x3\x12~\x7F\f\x10\x2\x2\x7F\x80\t\x3");
		sb.Append("\x2\x2\x80\x8B\x5\x4\x3\x11\x81\x82\f\xF\x2\x2\x82\x83\t\x4");
		sb.Append("\x2\x2\x83\x8B\x5\x4\x3\x10\x84\x85\f\xE\x2\x2\x85\x86\a\xE");
		sb.Append("\x2\x2\x86\x8B\x5\x4\x3\xF\x87\x88\f\r\x2\x2\x88\x89\a\xF\x2");
		sb.Append("\x2\x89\x8B\x5\x4\x3\xE\x8A{\x3\x2\x2\x2\x8A~\x3\x2\x2\x2\x8A");
		sb.Append("\x81\x3\x2\x2\x2\x8A\x84\x3\x2\x2\x2\x8A\x87\x3\x2\x2\x2\x8B");
		sb.Append("\x8E\x3\x2\x2\x2\x8C\x8A\x3\x2\x2\x2\x8C\x8D\x3\x2\x2\x2\x8D");
		sb.Append("\x5\x3\x2\x2\x2\x8E\x8C\x3\x2\x2\x2\x8F\x90\b\x4\x1\x2\x90\x91");
		sb.Append("\a-\x2\x2\x91\x9C\x3\x2\x2\x2\x92\x93\f\x4\x2\x2\x93\x94\a%");
		sb.Append("\x2\x2\x94\x9B\a-\x2\x2\x95\x96\f\x3\x2\x2\x96\x97\a\x17\x2");
		sb.Append("\x2\x97\x98\x5\x4\x3\x2\x98\x99\a\x18\x2\x2\x99\x9B\x3\x2\x2");
		sb.Append("\x2\x9A\x92\x3\x2\x2\x2\x9A\x95\x3\x2\x2\x2\x9B\x9E\x3\x2\x2");
		sb.Append("\x2\x9C\x9A\x3\x2\x2\x2\x9C\x9D\x3\x2\x2\x2\x9D\a\x3\x2\x2\x2");
		sb.Append("\x9E\x9C\x3\x2\x2\x2\x9F\xA0\a&\x2\x2\xA0\xA1\a-\x2\x2\xA1\xA2");
		sb.Append("\a\t\x2\x2\xA2\xA4\x5\f\a\x2\xA3\x9F\x3\x2\x2\x2\xA4\xA5\x3");
		sb.Append("\x2\x2\x2\xA5\xA3\x3\x2\x2\x2\xA5\xA6\x3\x2\x2\x2\xA6\xB5\x3");
		sb.Append("\x2\x2\x2\xA7\xA8\a\'\x2\x2\xA8\xAB\a-\x2\x2\xA9\xAA\a(\x2\x2");
		sb.Append("\xAA\xAC\a-\x2\x2\xAB\xA9\x3\x2\x2\x2\xAB\xAC\x3\x2\x2\x2\xAC");
		sb.Append("\xAD\x3\x2\x2\x2\xAD\xAE\a\x10\x2\x2\xAE\xB5\x5\x4\x3\x2\xAF");
		sb.Append("\xB1\x5\n\x6\x2\xB0\xAF\x3\x2\x2\x2\xB1\xB2\x3\x2\x2\x2\xB2");
		sb.Append("\xB0\x3\x2\x2\x2\xB2\xB3\x3\x2\x2\x2\xB3\xB5\x3\x2\x2\x2\xB4");
		sb.Append("\xA3\x3\x2\x2\x2\xB4\xA7\x3\x2\x2\x2\xB4\xB0\x3\x2\x2\x2\xB5");
		sb.Append("\t\x3\x2\x2\x2\xB6\xB7\a)\x2\x2\xB7\xB8\a-\x2\x2\xB8\xBA\a\x11");
		sb.Append("\x2\x2\xB9\xBB\x5\xE\b\x2\xBA\xB9\x3\x2\x2\x2\xBA\xBB\x3\x2");
		sb.Append("\x2\x2\xBB\xBC\x3\x2\x2\x2\xBC\xBF\a\x13\x2\x2\xBD\xBE\a(\x2");
		sb.Append("\x2\xBE\xC0\a-\x2\x2\xBF\xBD\x3\x2\x2\x2\xBF\xC0\x3\x2\x2\x2");
		sb.Append("\xC0\xC1\x3\x2\x2\x2\xC1\xC2\a\t\x2\x2\xC2\xC3\x5\x4\x3\x2\xC3");
		sb.Append("\v\x3\x2\x2\x2\xC4\xCE\a-\x2\x2\xC5\xC7\a\x15\x2\x2\xC6\xC8");
		sb.Append("\x5\xE\b\x2\xC7\xC6\x3\x2\x2\x2\xC7\xC8\x3\x2\x2\x2\xC8\xC9");
		sb.Append("\x3\x2\x2\x2\xC9\xCE\a\x16\x2\x2\xCA\xCB\a*\x2\x2\xCB\xCC\a");
		sb.Append("\x19\x2\x2\xCC\xCE\a-\x2\x2\xCD\xC4\x3\x2\x2\x2\xCD\xC5\x3\x2");
		sb.Append("\x2\x2\xCD\xCA\x3\x2\x2\x2\xCE\r\x3\x2\x2\x2\xCF\xD0\a-\x2\x2");
		sb.Append("\xD0\xD1\a(\x2\x2\xD1\xD8\a-\x2\x2\xD2\xD3\a\x12\x2\x2\xD3\xD4");
		sb.Append("\a-\x2\x2\xD4\xD5\a(\x2\x2\xD5\xD7\a-\x2\x2\xD6\xD2\x3\x2\x2");
		sb.Append("\x2\xD7\xDA\x3\x2\x2\x2\xD8\xD6\x3\x2\x2\x2\xD8\xD9\x3\x2\x2");
		sb.Append("\x2\xD9\xF\x3\x2\x2\x2\xDA\xD8\x3\x2\x2\x2\x1A%(\x31\x34\x42");
		sb.Append("\x45Ujruy\x8A\x8C\x9A\x9C\xA5\xAB\xB2\xB4\xBA\xBF\xC7\xCD\xD8");
	    return sb.ToString();
	}

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());


}
